/*
 * Main.java
 *
 * Created on April 3, 2007, 9:35 AM
 */

package edu.byu.isys413.cbb54.intex2kb.views;

import java.awt.Color;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.UIManager;

/**
 *
 * @author  Cameron
 */
public class Main extends javax.swing.JFrame {
    
    private TableModel model;
    
    /** Creates new form Main */
    public Main() {
        //        frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        // Set the selection background to yellow
        UIManager.put("Table.selectionBackground",Color.yellow );


        // Set the look and feel to the system's default
        try {
          UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch(Exception e) {
          System.out.println("Error setting native LAF: " + e);
        }
        
        // Insert the TableModel
        initComponents();
        model = new TableModel();
        jTable1.setModel(model);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Sale = new javax.swing.JPanel();
        Conversion = new javax.swing.JPanel();
        PrintOrder = new javax.swing.JPanel();
        Backup = new javax.swing.JPanel();
        Rental = new javax.swing.JPanel();
        Return = new javax.swing.JPanel();
        Repair = new javax.swing.JPanel();
        Default = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        table = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.X_AXIS));

        jPanel2.setLayout(new java.awt.CardLayout());

        Sale.setBackground(new java.awt.Color(255, 255, 255));
        Sale.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Sale.setMinimumSize(new java.awt.Dimension(250, 0));
        org.jdesktop.layout.GroupLayout SaleLayout = new org.jdesktop.layout.GroupLayout(Sale);
        Sale.setLayout(SaleLayout);
        SaleLayout.setHorizontalGroup(
            SaleLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 271, Short.MAX_VALUE)
        );
        SaleLayout.setVerticalGroup(
            SaleLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 442, Short.MAX_VALUE)
        );
        jPanel2.add(Sale, "card2");

        Conversion.setBackground(new java.awt.Color(255, 255, 255));
        Conversion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Conversion.setMinimumSize(new java.awt.Dimension(250, 0));
        org.jdesktop.layout.GroupLayout ConversionLayout = new org.jdesktop.layout.GroupLayout(Conversion);
        Conversion.setLayout(ConversionLayout);
        ConversionLayout.setHorizontalGroup(
            ConversionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 271, Short.MAX_VALUE)
        );
        ConversionLayout.setVerticalGroup(
            ConversionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 442, Short.MAX_VALUE)
        );
        jPanel2.add(Conversion, "card5");

        PrintOrder.setBackground(new java.awt.Color(255, 255, 255));
        PrintOrder.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PrintOrder.setMinimumSize(new java.awt.Dimension(250, 0));
        org.jdesktop.layout.GroupLayout PrintOrderLayout = new org.jdesktop.layout.GroupLayout(PrintOrder);
        PrintOrder.setLayout(PrintOrderLayout);
        PrintOrderLayout.setHorizontalGroup(
            PrintOrderLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 271, Short.MAX_VALUE)
        );
        PrintOrderLayout.setVerticalGroup(
            PrintOrderLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 442, Short.MAX_VALUE)
        );
        jPanel2.add(PrintOrder, "card3");

        Backup.setBackground(new java.awt.Color(255, 255, 255));
        Backup.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Backup.setMinimumSize(new java.awt.Dimension(250, 0));
        org.jdesktop.layout.GroupLayout BackupLayout = new org.jdesktop.layout.GroupLayout(Backup);
        Backup.setLayout(BackupLayout);
        BackupLayout.setHorizontalGroup(
            BackupLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 271, Short.MAX_VALUE)
        );
        BackupLayout.setVerticalGroup(
            BackupLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 442, Short.MAX_VALUE)
        );
        jPanel2.add(Backup, "card4");

        Rental.setBackground(new java.awt.Color(255, 255, 255));
        Rental.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Rental.setMinimumSize(new java.awt.Dimension(250, 0));
        org.jdesktop.layout.GroupLayout RentalLayout = new org.jdesktop.layout.GroupLayout(Rental);
        Rental.setLayout(RentalLayout);
        RentalLayout.setHorizontalGroup(
            RentalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 271, Short.MAX_VALUE)
        );
        RentalLayout.setVerticalGroup(
            RentalLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 442, Short.MAX_VALUE)
        );
        jPanel2.add(Rental, "card6");

        Return.setBackground(new java.awt.Color(255, 255, 255));
        Return.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Return.setMinimumSize(new java.awt.Dimension(250, 0));
        org.jdesktop.layout.GroupLayout ReturnLayout = new org.jdesktop.layout.GroupLayout(Return);
        Return.setLayout(ReturnLayout);
        ReturnLayout.setHorizontalGroup(
            ReturnLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 271, Short.MAX_VALUE)
        );
        ReturnLayout.setVerticalGroup(
            ReturnLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 442, Short.MAX_VALUE)
        );
        jPanel2.add(Return, "card7");

        Repair.setBackground(new java.awt.Color(255, 255, 255));
        Repair.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Repair.setMinimumSize(new java.awt.Dimension(250, 0));
        org.jdesktop.layout.GroupLayout RepairLayout = new org.jdesktop.layout.GroupLayout(Repair);
        Repair.setLayout(RepairLayout);
        RepairLayout.setHorizontalGroup(
            RepairLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 271, Short.MAX_VALUE)
        );
        RepairLayout.setVerticalGroup(
            RepairLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 442, Short.MAX_VALUE)
        );
        jPanel2.add(Repair, "card8");

        Default.setBackground(new java.awt.Color(255, 255, 255));
        Default.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        org.jdesktop.layout.GroupLayout DefaultLayout = new org.jdesktop.layout.GroupLayout(Default);
        Default.setLayout(DefaultLayout);
        DefaultLayout.setHorizontalGroup(
            DefaultLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 271, Short.MAX_VALUE)
        );
        DefaultLayout.setVerticalGroup(
            DefaultLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 442, Short.MAX_VALUE)
        );
        jPanel2.add(Default, "card9");

        jPanel5.add(jPanel2);

        jPanel6.setPreferredSize(new java.awt.Dimension(10, 100));
        org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 10, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 446, Short.MAX_VALUE)
        );
        jPanel5.add(jPanel6);

        getContentPane().add(jPanel5, java.awt.BorderLayout.EAST);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel1.setText("My Stuff");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setViewportView(jTable1);

        jPanel3.add(table, java.awt.BorderLayout.CENTER);

        jPanel7.setMinimumSize(new java.awt.Dimension(1, 1));
        org.jdesktop.layout.GroupLayout jPanel7Layout = new org.jdesktop.layout.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 10, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 446, Short.MAX_VALUE)
        );
        jPanel3.add(jPanel7, java.awt.BorderLayout.EAST);

        org.jdesktop.layout.GroupLayout jPanel8Layout = new org.jdesktop.layout.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 10, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 446, Short.MAX_VALUE)
        );
        jPanel3.add(jPanel8, java.awt.BorderLayout.WEST);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setMinimumSize(new java.awt.Dimension(100, 30));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 50));
        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 810, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 50, Short.MAX_VALUE)
        );
        getContentPane().add(jPanel4, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Backup;
    private javax.swing.JPanel Conversion;
    private javax.swing.JPanel Default;
    private javax.swing.JPanel PrintOrder;
    private javax.swing.JPanel Rental;
    private javax.swing.JPanel Repair;
    private javax.swing.JPanel Return;
    private javax.swing.JPanel Sale;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane table;
    // End of variables declaration//GEN-END:variables
    
    private void setVisible(int num){
        switch(num){
            case 1:
                Backup.setVisible(true);
                Conversion.setVisible(false);
                PrintOrder.setVisible(false);
                Rental.setVisible(false);
                Repair.setVisible(false);
                Return.setVisible(false);
                Sale.setVisible(false);
                Default.setVisible(false);
                break;
            case 2:
                Backup.setVisible(false);
                Conversion.setVisible(true);
                PrintOrder.setVisible(false);
                Rental.setVisible(false);
                Repair.setVisible(false);
                Return.setVisible(false);
                Sale.setVisible(false);
                Default.setVisible(false);
                break;
            case 3:
                Backup.setVisible(false);
                Conversion.setVisible(false);
                PrintOrder.setVisible(true);
                Rental.setVisible(false);
                Repair.setVisible(false);
                Return.setVisible(false);
                Sale.setVisible(false);
                Default.setVisible(false);
                break;
            case 4:
                Backup.setVisible(false);
                Conversion.setVisible(false);
                PrintOrder.setVisible(false);
                Rental.setVisible(true);
                Repair.setVisible(false);
                Return.setVisible(false);
                Sale.setVisible(false);
                Default.setVisible(false);
                break;
            case 5:
                Backup.setVisible(false);
                Conversion.setVisible(false);
                PrintOrder.setVisible(false);
                Rental.setVisible(false);
                Repair.setVisible(true);
                Return.setVisible(false);
                Sale.setVisible(false);
                Default.setVisible(false);
                break;
            case 6:
                Backup.setVisible(false);
                Conversion.setVisible(false);
                PrintOrder.setVisible(false);
                Rental.setVisible(false);
                Repair.setVisible(false);
                Return.setVisible(true);
                Sale.setVisible(false);
                Default.setVisible(false);
                break;
            case 7:
                Backup.setVisible(false);
                Conversion.setVisible(false);
                PrintOrder.setVisible(false);
                Rental.setVisible(false);
                Repair.setVisible(false);
                Return.setVisible(false);
                Sale.setVisible(true);
                Default.setVisible(false);
                break;
            default:
                Backup.setVisible(false);
                Conversion.setVisible(false);
                PrintOrder.setVisible(false);
                Rental.setVisible(false);
                Repair.setVisible(false);
                Return.setVisible(false);
                Sale.setVisible(false);
                Default.setVisible(true);
                break;
        }
    }
}
