/*
 * membershipEdit.java
 *
 * Created on February 27, 2007, 8:49 AM
 */

package edu.byu.isys413.cbb54.intex2kb.views;

import edu.byu.isys413.cbb54.intex2kb.data.ConnectionPool;
import edu.byu.isys413.cbb54.intex2kb.data.ConnectionPoolException;
import edu.byu.isys413.cbb54.intex2kb.data.Customer;
import edu.byu.isys413.cbb54.intex2kb.data.CustomerDAO;
import edu.byu.isys413.cbb54.intex2kb.data.DataException;
import edu.byu.isys413.cbb54.intex2kb.data.Membership;
import edu.byu.isys413.cbb54.intex2kb.data.MembershipDAO;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.LinkedList;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author  Cameron
 */
public class membershipEdit extends javax.swing.JFrame {
    
    SimpleDateFormat fmt = new SimpleDateFormat("dd-MMM-yy", Locale.US);
    Customer cust = null;
    Membership mem = null;
    
    /** Creates new form membershipEdit */
    public membershipEdit() {
        initComponents();
        try{
            getMembership();  
        } catch (DataException d){
            JOptionPane.showMessageDialog(null, "There was an error retrieving the Membership information");
            d.printStackTrace();
        }
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        BW = new javax.swing.JCheckBox();
        hdr = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cc1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ccExp1 = new javax.swing.JTextField();
        newsletter1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit Membership");
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.setPreferredSize(new java.awt.Dimension(100, 50));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(263, Short.MAX_VALUE)
                .addComponent(cancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(save)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(cancel))
                .addContainerGap())
        );
        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel6.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel6.setText("Interests:");

        BW.setText("B&W Photography");
        BW.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BW.setMargin(new java.awt.Insets(0, 0, 0, 0));

        hdr.setText("HDR Techniques");
        hdr.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        hdr.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BW)
                            .addComponent(hdr))))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(BW)
                .addGap(17, 17, 17)
                .addComponent(hdr)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel4.setText("Credit Card #");

        jLabel5.setText("Exp. Date");

        ccExp1.setColumns(5);

        newsletter1.setText("Receive Newsletter?");
        newsletter1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        newsletter1.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newsletter1)
                    .addComponent(cc1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ccExp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ccExp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newsletter1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cancelActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        Customer cust = CustomerDAO.getInstance().getHoldCustomer();
        
        try{
            Membership mem = MembershipDAO.getInstance().create(cust.getId());
            List<String> iList = new LinkedList<String>();
            mem.setCreditCard(cc1.getText());
            mem.setCcExpiration(ccExp1.getText());
            mem.setStartDate(fmt.format(System.currentTimeMillis()));
            if(newsletter1.isSelected()){
                mem.setNewsletter(true);
            }else{
                mem.setNewsletter(false);
            }
            
            if(BW.isSelected()){
                iList.add("0000011105caf55500f1fec0a80204");
            }
            if(hdr.isSelected()){
                iList.add("0000011105caf55f007a64c0a80204");
            }
            
            mem.setInterests(iList);
            MembershipDAO.getInstance().save(mem);
            cust.setMembership(mem);
            setVisible(false);
        } catch (Exception c){
            JOptionPane.showMessageDialog(null, "There was an error saving the Membership");
            c.printStackTrace();
        }
    }//GEN-LAST:event_saveActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new membershipEdit().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox BW;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField cc1;
    private javax.swing.JTextField ccExp1;
    private javax.swing.JCheckBox hdr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JCheckBox newsletter1;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
    
    private void getMembership() throws DataException {
        cust = CustomerDAO.getInstance().getHoldCustomer();
        Connection conn = null;
        
        try{
            
            conn = ConnectionPool.getInstance().get();
            mem = MembershipDAO.getInstance().getByCustomerID(cust.getId(),conn);
            
            cc1.setText(mem.getCreditCard());
            ccExp1.setText(mem.getCcExpiration());
            
            //release the connection
            conn.commit();
            ConnectionPool.getInstance().release(conn);
            
            if(mem.getNewsletter()){
                newsletter1.setSelected(true);
            }
            List<String> iList = new LinkedList<String>();
            iList = mem.getInterests();
            for(int i = 0; i < iList.size(); i++){
                String interest = iList.get(i);
                if(interest == "0000011105caf55500f1fec0a80204"){
                    BW.setSelected(true);
                }
                if(interest == "0000011105caf55f007a64c0a80204"){
                    hdr.setSelected(true);
                }
            }
            
        }catch (ConnectionPoolException e){
            throw new DataException("Could not get a connection to the database.");
        }catch (SQLException ex){
            throw new DataException("There was an retrieving the membership info");
        }
    }
}
